### ISSUE TITLE
Error with variables during mutation

### ISSUE THREAD

**Issue by JeresB** [marmelab/aor-simple-graphql-client#45]
When I try to update or create an element admin-on-rest doesn't variables provided.
![errorupdate](https://user-images.githubusercontent.com/26651896/28119785-539db3b8-6716-11e7-8d24-d2eae42f7622.png)
 The repo I use : https://github.com/JeresB/cuistot-aor
My Question on stackoverflow : https://stackoverflow.com/questions/45056706/admin-on-rest-error-data-format

**Comment by djhi** [comment]
That's because this client expect both create and update mutations to accept a single `data` parameter which contains your posted entity as a string (JSON.stringify). You must parse it server side. See https://github.com/marmelab/aor-simple-graphql-client#create-a-new-resource

Please note this project was a POC to explore aor integration with gql. We are working a on a better implementation here: https://github.com/marmelab/aor-graphql

**Comment by JeresB** [comment]
Thank you for your answer. I did fix this issue by parsing the data in the server side.
